spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

email:
  enabled: ${EMAIL_ENABLED:false}
  from: ${GMAIL_USERNAME:noreply@lxm.com}
  base-url: http://localhost:8080

auth:
  jwt:
    secret: jyLn8WGhNyR7fSHKPqPSrMCWbGW6x0EXRuqutT8nzg4=
    access-token:
      expiration-seconds: 3600  # 1시간
      issuer: "lxm-dev-api"
      audience: "lxm-dev-auth"
    password-reset-token:
      issuer: "lxm-dev-api"
      audience: "lxm-dev-auth"
      validity-in-seconds: 300
  refresh-token:
    ttl-hours: 24